[package]
name = "forex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
colored = "2.1.0"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.203", features = ["derive"] }
